Repository Ilkyoo/TeX-LEAN, pull requests merged in 2025-03, with the labels that each got.

#32 add *.pdf to .gitignore
  .gitignore
Labels: devops

#36 Add DF_15_2_7
  Formal/DF.lean
  Formal/DF_15/DF_15_2.lean
Labels: formalize exercise

#24 README for Github Desktop
  README (for github Desktop).md
Labels: documentation

#26 specific order groups are simple + reformatting 4.2.8
  Formal/DF.lean
  Formal/DF_4/DF_4_2.lean
  Formal/DF_4/DF_4_5.lean
Labels: formalize exercise

#43 remove tex & workflow
  .github/workflows/build.yml
  Informal/DF.pdf
  Informal/DF.tex
  Informal/DF_1/DF_1.tex
  Informal/DF_1/DF_1_4_1.tex
  Informal/DF_1/DF_1_4_2.tex
  Informal/DF_1/DF_1_4_3.tex
  Informal/DF_1/DF_1_4_4.tex
  Informal/DF_1/DF_1_4_5.tex
  Informal/DF_1/DF_1_4_6.tex
  Informal/DF_1/DF_1_4_7.tex
  Informal/DF_13/DF_13.tex
  Informal/DF_18/DF_18.tex
  Informal/DF_18/DF_18_1_1.tex
  Informal/DF_18/DF_18_1_2.tex
  Informal/DF_18/DF_18_1_3.tex
  Informal/DF_18/DF_18_1_4.tex
  Informal/DF_18/DF_18_1_5.tex
  Informal/DF_18/DF_18_3_1.tex
  Informal/DF_18/DF_18_3_2.tex
  Informal/DF_18/DF_18_3_3.tex
  Informal/DF_18/DF_18_3_4.tex
  Informal/DF_18/DF_18_3_5.tex
  Informal/DF_18/DF_18_3_6.tex
  Informal/DF_4/DF_4.tex
  Informal/DF_4/DF_4_2_1.tex
  Informal/DF_4/DF_4_2_2.tex
  Informal/DF_4/DF_4_2_3.tex
  Informal/DF_4/DF_4_2_4.tex
  Informal/DF_4/DF_4_2_5.tex
  Informal/DF_4/DF_4_2_6.tex
  Informal/DF_4/DF_4_2_7.tex
  Informal/DF_4/DF_4_2_8.tex
  Informal/DF_7/DF_7.tex
  Informal/DF_7/DF_7_1_1.tex
  Informal/DF_7/DF_7_1_2.tex
Labels: devops

#40 Add DF_4_4_2
  Formal/DF.lean
  Formal/DF_4/DF_4_4.lean
Labels: formalize exercise
